### ISSUE TITLE
Extension kills bitbucket

### ISSUE THREAD

**Issue by mirhagk** [lvivski/spectrum#3]
Having this extension enabled breaks bitbucket (specifically the merge pull request and resolve issue buttons which are core to it's functionality).

The reason this is to the best of my knowledge is because this extension inserts an SVG filter and bitbucket assumes that all children of the body are HTML elements. It iterates over them all and does `element.className.match`. SVG element's don't return a `className` that has a `match` function which breaks it.

I've [logged a bug with bitbucket](https://bitbucket.org/site/master/issues/13711/all-dialog-creation-buttons-merge-pr) since their code is fragile in this regard but I'm sure similar issues might be created on other sites.

I believe the idea proposed in #2 might be enough to fix this problem (so long as the extension isn't actually used on that page) and it'd go a long way towards ensuring that spectrum can't break random pages on the web (only making it possible to break pages that spectrum is actually used on).

Another solution perhaps could be a container div for the filter, or applying the filter at a level above the body, but I think that might be too specific to just bitbucket here. Could be a good short term solution if #2 is too much work

**Comment by lvivski** [comment]
Wow, thanks for finding that. I'm currently working on the next version which will only include SVG when needed. Additionally UI will be improved, and it would be easier to understand all the differences between the modes, but unfortunately no ETA yet.

**Comment by justtobetrendy** [comment]
FYI, this plugin  also breaks JIRA and Confluence (so basically any Atlassian web app) as none of their custom dialogs can be displayed.

**Comment by mirhagk** [comment]
I've submitted a pull request that fixes this by attaching the filter to the page only once needed. I'm not sure if I'm stepping on any toes in regards to the way you wanted to do things, but this seems to work from my testing and could be a fix for now.

**Comment by lvivski** [comment]
Thanks @mirhagk, I think that should work just fine as a quickfix!
