### ISSUE TITLE
Question about gamma correction

### ISSUE THREAD

**Issue by ounziw** [lvivski/spectrum#5]
Thank you for a good chrome addon.

I have a question.

The code seems to apply gamma correction  exponent=".9"

> 				<feFuncB type="gamma" exponent=".9"/>
> 				<feFuncR type="gamma" exponent=".9"/>
> 				<feFuncG type="gamma" exponent=".9"/>

I'm not sure where .9 comes from.
Could you tell me the reason?

**Comment by lvivski** [comment]
Initally, gamma correction was added to fix some gamma inconsistencies between Mac and Windows. It was later removed.
